//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursos
    {
        public int Id_Curso { get; set; }
        public string Descripcion { get; set; }
        public int Id_Modalidad { get; set; }
        public decimal Costo { get; set; }
        public int Id_Pais { get; set; }
        public int Id_Ciudad { get; set; }
        public string Direccion { get; set; }
    
        public virtual Catalogos Catalogos { get; set; }
        public virtual Catalogos Catalogos1 { get; set; }
        public virtual Catalogos Catalogos2 { get; set; }
    }
}
