//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTest.WCFCursosClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListCurso", Namespace="http://schemas.datacontract.org/2004/07/WCFPrueba")]
    [System.SerializableAttribute()]
    public partial class ListCurso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Curso {
            get {
                return this.Id_CursoField;
            }
            set {
                if ((this.Id_CursoField.Equals(value) != true)) {
                    this.Id_CursoField = value;
                    this.RaisePropertyChanged("Id_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modalidad {
            get {
                return this.ModalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.ModalidadField, value) != true)) {
                    this.ModalidadField = value;
                    this.RaisePropertyChanged("Modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://schemas.datacontract.org/2004/07/WCFPrueba")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_PaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Costo {
            get {
                return this.CostoField;
            }
            set {
                if ((this.CostoField.Equals(value) != true)) {
                    this.CostoField = value;
                    this.RaisePropertyChanged("Costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Ciudad {
            get {
                return this.Id_CiudadField;
            }
            set {
                if ((this.Id_CiudadField.Equals(value) != true)) {
                    this.Id_CiudadField = value;
                    this.RaisePropertyChanged("Id_Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Curso {
            get {
                return this.Id_CursoField;
            }
            set {
                if ((this.Id_CursoField.Equals(value) != true)) {
                    this.Id_CursoField = value;
                    this.RaisePropertyChanged("Id_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Modalidad {
            get {
                return this.Id_ModalidadField;
            }
            set {
                if ((this.Id_ModalidadField.Equals(value) != true)) {
                    this.Id_ModalidadField = value;
                    this.RaisePropertyChanged("Id_Modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Pais {
            get {
                return this.Id_PaisField;
            }
            set {
                if ((this.Id_PaisField.Equals(value) != true)) {
                    this.Id_PaisField = value;
                    this.RaisePropertyChanged("Id_Pais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Catalogo", Namespace="http://schemas.datacontract.org/2004/07/WCFPrueba")]
    [System.SerializableAttribute()]
    public partial class Catalogo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ElementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_GrupoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Elemento {
            get {
                return this.Id_ElementoField;
            }
            set {
                if ((this.Id_ElementoField.Equals(value) != true)) {
                    this.Id_ElementoField = value;
                    this.RaisePropertyChanged("Id_Elemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Grupo {
            get {
                return this.Id_GrupoField;
            }
            set {
                if ((this.Id_GrupoField.Equals(value) != true)) {
                    this.Id_GrupoField = value;
                    this.RaisePropertyChanged("Id_Grupo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFCursosClient.IWCFCursos")]
    public interface IWCFCursos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getList", ReplyAction="http://tempuri.org/IWCFCursos/getListResponse")]
        AppTest.WCFCursosClient.ListCurso[] getList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getList", ReplyAction="http://tempuri.org/IWCFCursos/getListResponse")]
        System.Threading.Tasks.Task<AppTest.WCFCursosClient.ListCurso[]> getListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getId", ReplyAction="http://tempuri.org/IWCFCursos/getIdResponse")]
        AppTest.WCFCursosClient.Curso getId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getId", ReplyAction="http://tempuri.org/IWCFCursos/getIdResponse")]
        System.Threading.Tasks.Task<AppTest.WCFCursosClient.Curso> getIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/Set", ReplyAction="http://tempuri.org/IWCFCursos/SetResponse")]
        int Set(AppTest.WCFCursosClient.Curso Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/Set", ReplyAction="http://tempuri.org/IWCFCursos/SetResponse")]
        System.Threading.Tasks.Task<int> SetAsync(AppTest.WCFCursosClient.Curso Curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/Delete", ReplyAction="http://tempuri.org/IWCFCursos/DeleteResponse")]
        int Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/Delete", ReplyAction="http://tempuri.org/IWCFCursos/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllModalidades", ReplyAction="http://tempuri.org/IWCFCursos/getAllModalidadesResponse")]
        AppTest.WCFCursosClient.Catalogo[] getAllModalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllModalidades", ReplyAction="http://tempuri.org/IWCFCursos/getAllModalidadesResponse")]
        System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllModalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllPaises", ReplyAction="http://tempuri.org/IWCFCursos/getAllPaisesResponse")]
        AppTest.WCFCursosClient.Catalogo[] getAllPaises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllPaises", ReplyAction="http://tempuri.org/IWCFCursos/getAllPaisesResponse")]
        System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllPaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllCiudades", ReplyAction="http://tempuri.org/IWCFCursos/getAllCiudadesResponse")]
        AppTest.WCFCursosClient.Catalogo[] getAllCiudades(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFCursos/getAllCiudades", ReplyAction="http://tempuri.org/IWCFCursos/getAllCiudadesResponse")]
        System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllCiudadesAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFCursosChannel : AppTest.WCFCursosClient.IWCFCursos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFCursosClient : System.ServiceModel.ClientBase<AppTest.WCFCursosClient.IWCFCursos>, AppTest.WCFCursosClient.IWCFCursos {
        
        public WCFCursosClient() {
        }
        
        public WCFCursosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFCursosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCursosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFCursosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AppTest.WCFCursosClient.ListCurso[] getList() {
            return base.Channel.getList();
        }
        
        public System.Threading.Tasks.Task<AppTest.WCFCursosClient.ListCurso[]> getListAsync() {
            return base.Channel.getListAsync();
        }
        
        public AppTest.WCFCursosClient.Curso getId(int id) {
            return base.Channel.getId(id);
        }
        
        public System.Threading.Tasks.Task<AppTest.WCFCursosClient.Curso> getIdAsync(int id) {
            return base.Channel.getIdAsync(id);
        }
        
        public int Set(AppTest.WCFCursosClient.Curso Curso) {
            return base.Channel.Set(Curso);
        }
        
        public System.Threading.Tasks.Task<int> SetAsync(AppTest.WCFCursosClient.Curso Curso) {
            return base.Channel.SetAsync(Curso);
        }
        
        public int Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public AppTest.WCFCursosClient.Catalogo[] getAllModalidades() {
            return base.Channel.getAllModalidades();
        }
        
        public System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllModalidadesAsync() {
            return base.Channel.getAllModalidadesAsync();
        }
        
        public AppTest.WCFCursosClient.Catalogo[] getAllPaises() {
            return base.Channel.getAllPaises();
        }
        
        public System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllPaisesAsync() {
            return base.Channel.getAllPaisesAsync();
        }
        
        public AppTest.WCFCursosClient.Catalogo[] getAllCiudades(int id) {
            return base.Channel.getAllCiudades(id);
        }
        
        public System.Threading.Tasks.Task<AppTest.WCFCursosClient.Catalogo[]> getAllCiudadesAsync(int id) {
            return base.Channel.getAllCiudadesAsync(id);
        }
    }
}
